### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-AndreaFCR#1]
Muy buen trabajo @AndreaFCR!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 300 / 347
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Necesitamos dos etiquetas `a` en el menu, dentro de los `li`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.wrapper { padding: 10px }`
- [x] CSS > COLOR: El color de los enlaces debe ser  4a4a4a
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by AndreaFCR** [comment]
Hola Miguel, 

Tengo dudas en cuanto a estos puntos del issue:

-En el ejercicio tenemos 3: uno para cargar las fuentes de google fonts y otros dos para el reset.css y el main.css
> HTML > LINK: Debemos tener dos ficheros de estilos importados con un link.

-Estos creo que van relacionados.  He puesto en title en el <a>, ¿así no se puede hacer? 
>  HTML > HEADER: La etiqueta img debe tener el atributo title.

-Tengo dos etiquetas <a> en el menú, para blog y para contacto
>  HTML > HEADER: Necesitamos dos etiquetas a en el menu, dentro de los li.

-En este caso, sí lo tengo cambiado con css (en html lo tengo así "creando diversidad digital"):
> HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.

-Tengo definido el tamaño de la fuente para cada uno de los <span> que divide el <h1>. Es correcto de esta manera? Porque efectivamente el tamaño en mobile es 30px y el tamaño en tablet es de 40px. 
>CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
>CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.

Muchas gracias!!
